### ISSUE TITLE
Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by anagram3k** [mysticatea/eslint-plugin-node#150]
This happens when editing the file.
OBS: WebUtil.js is a file, not a directory

Trace:
```
[Error - 9:20:57 AM] Error: ENOTDIR: not a directory, stat 'src/utils/WebUtil.js/index.js.js.js.js.js'
    at fs.statSync (fs.js:953:3)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at exists (/home/luis/git/mobile-excel/node_modules/eslint-plugin-node/lib/util/exists.js:46:20)
    at checkForExistence (/home/luis/git/mobile-excel/node_modules/eslint-plugin-node/lib/util/check-existence.js:29:43)
    at Program:exit (/home/luis/git/mobile-excel/node_modules/eslint-plugin-node/lib/rules/no-missing-require.js:44:17)
    at listeners.(anonymous function).forEach.listener (/home/luis/git/mobile-excel/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/luis/git/mobile-excel/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/luis/git/mobile-excel/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/luis/git/mobile-excel/node_modules/eslint/lib/util/node-event-generator.js:280:22)
```
Package versions:
```
├─┬ eslint@5.13.0
│ ├─┬ eslint-scope@4.0.0
│ ├── eslint-utils@1.3.1
│ ├── eslint-visitor-keys@1.0.0
│ │ └── eslint-visitor-keys@1.0.0 deduped
├── eslint-config-google@0.12.0
├─┬ eslint-config-prettier@4.0.0
├─┬ eslint-plugin-import@2.16.0
│ ├─┬ eslint-import-resolver-node@0.3.2
│ ├─┬ eslint-module-utils@2.3.0
├─┬ eslint-plugin-lodash@5.1.0
├─┬ eslint-plugin-node@8.0.1
│ ├─┬ eslint-plugin-es@1.4.0
│ │ ├── eslint-utils@1.3.1 deduped
│ ├── eslint-utils@1.3.1 deduped
├─┬ eslint-plugin-prettier@3.0.1
├── eslint-plugin-promise@4.0.1
├─┬ eslint-plugin-security@1.4.0
```

.eslintrc.json
```javascript
{
  "extends": [
    "eslint:recommended",
    "plugin:node/recommended",
    "google",
    "prettier",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:security/recommended",
    "plugin:promise/recommended",
    "plugin:lodash/recommended"
  ],
  "plugins": [
    "prettier",
    "import",
    "security",
    "promise",
    "lodash"
  ],
  "env": {
    "node": true,
    "es6": true
  },
  "rules": {
    "prettier/prettier": "error",
    "lodash/prefer-lodash-method": [2, { "ignoreMethods": ["split"] }],
    "require-jsdoc": "off"
  }
}
```

**Comment by mysticatea** [comment]
Thank you for this report.

I'm not sure what happened. Would you provide small repro steps in order to that I reproduce it?

**Comment by anagram3k** [comment]
Please disregard, It was an error on my code. 
You can close the issue.
